export const LOGIN_SCREEN = 'LOGIN';
export const SIGNUP_SCREEN = 'SIGNUP';

export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';

export const AUTH_SIGN_IN_REQUESTED = 'AUTH_SIGN_IN_REQUESTED';
export const AUTH_SIGN_IN_SUCCESS = 'AUTH_SIGN_IN_SUCCESS';
export const AUTH_SIGN_IN_FAILED = 'AUTH_SIGN_IN_FAILED';
