export const LOGIN_SCREEN = 'LOGIN';
export const SIGNUP_SCREEN = 'SIGNUP';

export const AUTH_SIGN_OUT_REQUESTED = 'AUTH_SIGN_OUT_REQUESTED';
export const AUTH_SIGN_OUT_SUCCESS = 'AUTH_SIGN_OUT_SUCCESS';

export const AUTH_SIGN_IN_REQUESTED = 'AUTH_SIGN_IN_REQUESTED';
export const AUTH_SIGN_IN_SUCCESS = 'AUTH_SIGN_IN_SUCCESS';
export const AUTH_SIGN_IN_FAILED = 'AUTH_SIGN_IN_FAILED';
