export const SAVE_ALL_CHANNELS_LIST = 'SAVE_ALL_CHANNELS_LIST';

export const ADD_CHANNEL_REQUESTED = 'ADD_CHANNEL_REQUESTED';
export const ADD_CHANNEL_SUCCESS = 'ADD_CHANNEL_SUCCESS';
export const ADD_CHANNEL_FAILED = 'ADD_CHANNEL_FAILED';

export const REMOVE_CHANNEL_REQUESTED = 'REMOVE_CHANNEL_REQUESTED';
export const REMOVE_CHANNEL_SUCCESS = 'REMOVE_CHANNEL_SUCCESS';
export const REMOVE_CHANNEL_FAILED = 'REMOVE_CHANNEL_FAILED';

export const CHANNEL_MESSAGES_REQUESTED = 'CHANNEL_MESSAGES_REQUESTED';
export const CHANNEL_MESSAGES_FAILED = 'CHANNEL_MESSAGES_FAILED';
export const CHANNEL_MESSAGES_SUCCESS = 'CHANNEL_MESSAGES_SUCCESS';
