export const SAVE_ALL_SERVERS_LIST = 'SAVE_ALL_SERVERS_LIST';

export const SERVER_DETAILS_REQUESTED = 'SERVER_DETAILS_REQUESTED';
export const SERVER_DETAILS_FAILED = 'SERVER_DETAILS_FAILED';
export const SERVER_DETAILS_SUCCESS = 'SERVER_DETAILS_SUCCESS';

export const JOIN_SERVER_REQUESTED = 'JOIN_SERVER_REQUESTED';
export const JOIN_SERVER_FAILED = 'JOIN_SERVER_FAILED';
export const JOIN_SERVER_SUCCESS = 'JOIN_SERVER_SUCCESS';

export const REMOVE_SERVER = 'REMOVE_SERVER';
export const SAVE_INVITE_URL = 'SAVE_INVITE_URL';

export const ServerTypes = {
  PRIVATE: 'private',
  PUBLIC: 'public',
};

export const serverValidation = {
  SERVER_NAME_MIN_LENGTH: 3,
  SERVER_NAME_MAX_LENGTH: 120,
  SERVER_DESCRIPTION_MAX_LENGTH: 2000,
};

export const EXPLORE_SERVERS_REQUESTED = 'EXPLORE_SERVERS_REQUESTED';
export const EXPLORE_SERVERS_FAILED = 'EXPLORE_SERVERS_FAILED';
export const EXPLORE_SERVERS_SUCCESS = 'EXPLORE_SERVERS_SUCCESS';

export const ADD_EXPLORE_SERVER_DATA = 'ADD_EXPLORE_SERVER_DATA';
export const RESET_EXPLORE_SERVER = 'RESET_EXPLORE_SERVER';

export const CREATE_SERVER_REQUESTED = 'CREATE_SERVER_REQUESTED';
export const CREATE_SERVER_FAILED = 'CREATE_SERVER_FAILED';
export const CREATE_SERVER_SUCCESS = 'CREATE_SERVER_SUCCESS';
export const CREATE_SERVER_RESET = 'CREATE_SERVER_RESET';
