export const SAVE_ALL_SERVERS_LIST = 'SAVE_ALL_SERVERS_LIST';

export const SERVER_DETAILS_REQUESTED = 'SERVER_DETAILS_REQUESTED';
export const SERVER_DETAILS_FAILED = 'SERVER_DETAILS_FAILED';
export const SERVER_DETAILS_SUCCESS = 'SERVER_DETAILS_SUCCESS';

export const ADD_SERVER = 'ADD_SERVER';
export const REMOVE_SERVER = 'REMOVE_SERVER';
export const SAVE_INVITE_URL = 'SAVE_INVITE_URL';
