export const CONNECT_ALL_SERVERS = 'CONNECT_ALL_SERVERS';

export const CONNECT_SINGLE_SERVER = 'CONNECT_SINGLE_SERVER';
export const DISCONNECT_SINGLE_SERVER = 'DISCONNECT_SINGLE_SERVER';

export const SEND_CHANNEL_MESSAGE = 'SEND_CHANNEL_MESSAGE';
export const NEW_CHANNEL_MESSAGE = 'NEW_CHANNEL_MESSAGE';
