export const CONNECT_ALL_SERVERS = 'CONNECT_ALL_SERVERS';

export const CONNECT_SINGLE_SERVER = 'CONNECT_SINGLE_SERVER';
export const DISCONNECT_SINGLE_SERVER = 'DISCONNECT_SINGLE_SERVER';

export const SEND_CHANNEL_MESSAGE = 'SEND_CHANNEL_MESSAGE';
export const NEW_CHANNEL_MESSAGE = 'NEW_CHANNEL_MESSAGE';

export const SERVER_OWNER_TRANSFERRED = 'SERVER_OWNER_TRANSFERRED';
export const SERVER_USER_KICKED_OUT = 'SERVER_USER_KICKED_OUT';
export const SERVER_MEMBER_LEFT = 'SERVER_MEMBER_LEFT';
export const SERVER_MEMBER_ROLE_UPDATED = 'SERVER_MEMBER_ROLE_UPDATED';
export const NEW_SERVER_MEMBER_JOINED = 'NEW_SERVER_MEMBER_JOINED';

export const SERVER_CREATED = 'SERVER_CREATED';
export const SERVER_UPDATED = 'SERVER_UPDATED';
export const SERVER_DELETED = 'SERVER_DELETED';

export const SERVER_CHANNEL_CREATED = 'SERVER_CHANNEL_CREATED';
export const SERVER_CHANNEL_UPDATED = 'SERVER_CHANNEL_UPDATED';
export const SERVER_CHANNEL_DELETED = 'SERVER_CHANNEL_DELETED';

export const USER_DETAILS_UPDATED = 'USER_DETAILS_UPDATED';

export const SESSION_EXPIRED = 'SESSION_EXPIRED';
